version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build:
    working_directory: closet-space-ui
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
        key: closet-space-ui-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
        key: closet-space-ui-{{ .Branch }}-{{ checksum "package-lock.json" }}
        paths:
          - "node_modules"
      - run: npm run test -- --watch=false --progress=false --browsers=ChromeHeadlessCI
      - run: npm run e2e -- --protractor-config=./e2e/protractor-ci.conf.js
workflows:
  build:
    jobs:
      - build-and-test
