name: Master Deployment Workflow

on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
  release:
    types: 
      -created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: NPM Tests
      uses: anna-money/github-actions-npm@v1
    - name: Run a multi-line script
      run: |
        npm run ng serve
